name: Auto Update AI News

on:
  # Run twice daily at 05:00 and 17:00 UTC
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC daily
    - cron: '0 17 * * *'  # 17:00 UTC daily
  
  # Allow manual triggering for testing
  workflow_dispatch:

# Set permissions for the workflow
permissions:
  contents: write  # Required to commit and push changes

jobs:
  collect-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Cache pip dependencies for faster builds
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run news collector
        run: |
          python collector/generate_news.py --verbose
        continue-on-error: false  # Fail workflow if collection fails
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Commit and push changes
        run: |
          # Add all changes in data directory
          git add data/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Create commit with timestamp
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
            git commit -m "Auto-update: ${TIMESTAMP}"
            
            # Push with retry logic
            for i in {1..3}; do
              if git push; then
                echo "Successfully pushed changes"
                break
              else
                echo "Push failed, retrying in 5 seconds... (attempt $i/3)"
                sleep 5
              fi
            done
          fi
      
      - name: Create error log on failure
        if: failure()
        run: |
          echo "Collection failed at $(date -u +"%Y-%m-%d %H:%M UTC")" >> data/error.log
          echo "Workflow run: ${{ github.run_id }}" >> data/error.log
          git add data/error.log
          git commit -m "Error log: Collection failed" || true
          git push || true
